name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  
jobs:
  dockerbuild:
    uses: CivicAIPortal/dev-ops/.github/workflows/docker.yml@main
    secrets: inherit
    with: 
      dockerfile: "deployment/docker/Dockerfile"
      harbor_config: "deployment/harbor.config"
  
  helm-setup:
    uses: CivicAIPortal/dev-ops/.github/workflows/build-context.yml@main
    secrets: inherit
  
  helm:
    needs: helm-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.0

      - name: Find and Push Helm Charts
        env:
          HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
          HARBOR_CREDENTIALS: ${{ secrets.HARBOR_CREDENTIALS }}
        run: |
          git clone https://x-access-token:${{ secrets.DEV_OPS_PAT }}@github.com/CivicAIPortal/dev-ops.git devops
          chmod +x ./devops/scripts/harborconfig.sh
          . ./devops/scripts/harborconfig.sh deployment/helm/harbor.config

          helm registry login "$HARBOR_HOST" \
            --username "$HARBOR_USERNAME" \
            --password "$HARBOR_PASSWORD"

          CHART_DIR="deployment/helm"
          cd "$CHART_DIR"
          echo "Build Dependencies"
          IMAGE_TAG="${{ needs.helm-setup.outputs.image_tag }}"
          sed -i.bak -E "s/^(version: .+)-tag$/\1-${IMAGE_TAG}/" Chart.yaml
          helm dependency build
          echo "Build Chart"
          helm package .

          CHART_NAME=$(grep '^name:' Chart.yaml | awk '{print $2}')
          PACKAGE_FILE="${CHART_NAME}-*.tgz"
          echo "Push Chart"
          helm push $PACKAGE_FILE oci://$HARBOR_HOST/$HARBOR_PROJECT
